version: "3"

networks:
  cfssl:
    external: false

services:
  cfssl:
    build:
      context: .
      dockerfile: Dockerfile
    image: example-cfssl:latest
    container_name: example-cfssl
    networks:
      - cfssl
    volumes:
      - ca-volume:/etc/cfssl
    restart: unless-stopped
    command: serve -config /etc/cfssl/ca-config.json -ca-key /etc/cfssl/example-ca-key.pem -ca /etc/cfssl/example-ca.pem -address=0.0.0.0 -db-config=/etc/cfssl/db-config.json
  proxy:
    image: nginx:latest
    container_name: ca-proxy
    restart: unless-stopped
    depends_on:
      - cfssl
    networks:
      - cfssl
    volumes:
      - ${PWD}/ca-proxy.conf:/etc/nginx/conf.d/ca-proxy.conf
      - ca-volume:/data/custom_ssl
    ports:
      - "10.1.10.10:8443:443"

volumes:
  ca-volume: